### ISSUE TITLE
pymcts sister project has very similar goals

### ISSUE THREAD

**Issue by dbravender** [dbravender/mittmcts#1]
@smallnamespace I noticed your https://github.com/smallnamespace/pymcts project and it looks like it has very similar goals to my project https://github.com/dbravender/mittmcts. Just wanted to let you know it was there. Cheers!

**Comment by smallnamespace** [comment]
Thanks for the heads up :) Do you have a particular use case in mind for mittmcts? I think it's cool that you've already implemented ISMCTS, as (one) eventual use case for me is to train board evaluators for an imperfect information game.

**Comment by dbravender** [comment]
The goal is to add tools that aid with the analysis of existing games and helping board game designers do simulated play testing and analysis of games they are working on.

**Comment by smallnamespace** [comment]
So someone could code up the rules for a board game, and then use the tools to see how balanced/fair the rules are?

My end goal is pretty similar, but more focused on computer games and building AIs.

**Comment by dbravender** [comment]
Cool. I hope you have as much fun working on your project as I am working on mine. I have learned a lot. Cheers!
