### ISSUE TITLE
Document get_moves() return values

### ISSUE THREAD

**Issue by donkirkby** [dbravender/mittmcts#7]
Thanks for sharing the project.
The documentation is pretty good, but the README file says that `get_moves()` should return a list of moves. However, the code expects `is_random` and the list of moves. I haven't yet figured out what `is_random` is for, but the Connect Four example returns `False`.

**Comment by dbravender** [comment]
Thanks for catching this @donkirkby!

I added (hopefully) better documentation about `get_moves` in 80d2e5f2bd4089c8dd5d69b794a74b017ba6ad74. `is_random` is there for games that branch where the players don't have a choice in the branch that is selected (like a die roll).
